using System.Net;
using System.Net.Http.Json;
using BookmarkFeeder.WebApi.Dtos;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;

namespace BookmarkFeeder.WebApi.Tests.Infrastructure;

/// <summary>
/// The SearchVector column is generated by PostgreSQL itself, so nothing about it can be
/// verified without a real database — EF InMemory has no tsvector, no setweight, no GIN.
/// </summary>
[Trait("Category", "Integration")]
public class SearchVectorTests(PostgresApiFactory factory) : IClassFixture<PostgresApiFactory>
{
    private async Task<BookmarkDto> CreateBookmark(HttpClient client, CreateBookmarkRequest request)
    {
        var response = await client.PostAsJsonAsync("/api/bookmarks", request);
        response.StatusCode.Should().Be(HttpStatusCode.Created);
        return (await response.Content.ReadFromJsonAsync<BookmarkDto>())!;
    }

    private async Task<string> ReadSearchVector(Guid id)
    {
        await using var db = factory.CreateContext();
        // EF's scalar SqlQuery requires the column to be aliased "Value".
        return await db.Database
            .SqlQuery<string>($@"SELECT ""SearchVector""::text AS ""Value"" FROM ""Bookmarks"" WHERE ""Id"" = {id}")
            .SingleAsync();
    }

    [Fact]
    public async Task SearchVector_IsPopulated_OnInsert()
    {
        var client = factory.CreateAuthenticatedClient();
        var created = await CreateBookmark(client, new CreateBookmarkRequest(
            $"https://vec-{Guid.NewGuid():N}.example.com/serialization",
            "Kestrel performance tuning",
            "Notes about throughput",
            null, null, null, null));

        var vector = await ReadSearchVector(created.Id);

        vector.Should().NotBeNullOrWhiteSpace();
        // Stemmed by the 'english' configuration: "tuning" -> "tune".
        vector.Should().Contain("tune");
    }

    [Fact]
    public async Task SearchVector_WeightsTitleA_DescriptionB_UrlC()
    {
        var client = factory.CreateAuthenticatedClient();
        var token = Guid.NewGuid().ToString("N")[..8];
        var created = await CreateBookmark(client, new CreateBookmarkRequest(
            $"https://example.com/{token}urlword",
            $"{token}titleword",
            $"{token}descword",
            null, null, null, null));

        var vector = await ReadSearchVector(created.Id);

        // Weight letters are what make ranking favour a title hit over a url hit.
        vector.Should().Contain($"'{token}titleword':1A");
        vector.Should().MatchRegex($@"'{token}descword':\d+B");
        vector.Should().MatchRegex($@"'{token}urlword':\d+C");
    }

    [Fact]
    public async Task SearchVector_IsRecomputed_WhenTitleChanges()
    {
        var client = factory.CreateAuthenticatedClient();
        var created = await CreateBookmark(client, new CreateBookmarkRequest(
            $"https://upd-{Guid.NewGuid():N}.example.com", "Original heading", null, null, null, null, null));

        (await ReadSearchVector(created.Id)).Should().Contain("origin");

        var update = new UpdateBookmarkRequest("Replaced heading", null, null, null, null, null);
        (await client.PutAsJsonAsync($"/api/bookmarks/{created.Id}", update))
            .StatusCode.Should().Be(HttpStatusCode.OK);

        var vector = await ReadSearchVector(created.Id);
        vector.Should().Contain("replac");
        vector.Should().NotContain("origin");
    }

    [Fact]
    public async Task SearchVector_IndexesUrlWordsIndividually_NotAsHostTokens()
    {
        var client = factory.CreateAuthenticatedClient();
        var token = Guid.NewGuid().ToString("N")[..8];
        // Postgres' parser would index this as the host token "{token}wolverine.netlify.app",
        // leaving a search for the bare product name unmatched — the ILIKE search we're
        // replacing did match it, so the vector must keep the segments separately searchable.
        var created = await CreateBookmark(client, new CreateBookmarkRequest(
            $"https://{token}wolverine.netlify.app/guide", "Untitled", null, null, null, null, null));

        var vector = await ReadSearchVector(created.Id);

        vector.Should().MatchRegex($@"'{token}wolverine':\d+C");
        vector.Should().MatchRegex(@"'guid\w*':\d+C");
    }

    [Fact]
    public async Task SearchVector_IsAStoredGeneratedColumn()
    {
        await using var db = factory.CreateContext();

        var isGenerated = await db.Database.SqlQuery<string>(
            $@"SELECT is_generated AS ""Value"" FROM information_schema.columns
               WHERE table_name = 'Bookmarks' AND column_name = 'SearchVector'").SingleAsync();

        // ALWAYS => Postgres maintains it; no application code can drift it out of sync.
        isGenerated.Should().Be("ALWAYS");
    }

    [Fact]
    public async Task SearchVector_HasGinIndex()
    {
        await using var db = factory.CreateContext();

        var indexDefs = await db.Database.SqlQuery<string>(
            $@"SELECT indexdef AS ""Value"" FROM pg_indexes
               WHERE tablename = 'Bookmarks' AND indexdef LIKE '%SearchVector%'").ToListAsync();

        indexDefs.Should().ContainSingle().Which.Should().Contain("USING gin");
    }
}
